apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-service
spec:
  selector:
    app: springboot-docker
  ports:
protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
